#!/bin/sh
### BEGIN INIT INFO
# Provides:		firewall rules
# Required-Start:	$remote_fs $syslog
# Required-stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description	Firewall deamon
# Description		Enable service provided by daemon.
### END INIT INFO

# Suprimer toutes les regles
sudo iptables -t filter -F
sudo iptables -t filter -X
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t mangle -F
sudo iptables -t mangle -X

#Bloquer tout les trafic
sudo iptables -P INPUT DROP
sudo iptables -P FORWARD DROP
sudo iptables -P OUTPUT DROP

#Autoriser les connexion localhost
sudo iptables -t filter -A INPUT -i lo -j ACCEPT
sudo iptables -t filter -A OUTPUT -o lo -j ACCEPT

#Autoriser serveur dns
sudo iptables -t filter -A OUTPUT -p udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
sudo iptables -t filter -A INPUT -p udp --sport 53 -m conntrack --ctstate ESTABLISHED -j ACCEPT

#ping (ICMP)
sudo iptables -t filter -A INPUT -p icmp -j ACCEPT
sudo iptables -t filter -A OUTPUT -p icmp -j ACCEPT

# Connexions etablies
sudo iptables -A INPUT -m state --state ESTABLISHED -j ACCEPT
sudo iptables -A OUTPUT -m state --state ESTABLISHED -j ACCEPT

#SSH
sudo iptables -t filter -A INPUT -p tcp --dport 2323 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 2323 -j ACCEPT

#navigation web pour apt
#sudo iptables -t filter -A OUTPUT -p tcp -m multiport --dports 80,443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
#sudo iptables -t filter -A INPUT -p tcp -m multiport --sports 80,443 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT

sudo iptables -t filter -A INPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 80 -j ACCEPT
sudo iptables -t filter -A INPUT -p tcp --dport 443 -j ACCEPT
sudo iptables -t filter -A OUTPUT -p tcp --dport 443 -j ACCEPT

#Protection DOS limite 1 demande de connextion par seconde
sudo iptables -A FORWARD -p tcp --syn -m limit --limit 1/second -j ACCEPT

#Protection DOS pareil mais pour les protocoles UDP ICMP
sudo iptables -A FORWARD -p udp -m limit --limit 1/second -j ACCEPT
sudo iptables -A FORWARD -p icmp --icmp-type echo-request -m limit --limit 1/second -j ACCEPT

#Protection anti brut force ssh
sudo iptables -A INPUT -p tcp --dport 2323 -m conntrack --ctstate NEW -m recent --set
sudo iptables -A INPUT -p tcp --dport 2323 -m conntrack --ctstate NEW -m recent --update --seconds 3 --hitcount 2 -j DROP

#Protection anti scan
sudo iptables -N port-scanning
sudo iptables -A port-scanning -p tcp --tcp-flags SYN,ACK,FIN,RST RST -m limit --limit 1/s --limit-burst 2 -j RETURN
sudo iptables -A port-scanning -j DROP
